---
- name: "Generate Keypair"
  ec2_key:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}" 
    name: "{{ keypair_name }}"
    region: "{{ region }}"
    key_material: "{{ lookup('file', aws_public_ssh_key) }}"
#    key_material: "{{ lookup('file', 'home/dsteffen/Development/ssh_keys/aws/aws.pub') }}"

- name: Create a security group
  ec2_group:
    name: "{{ security_group }}"
    description: The webservers security group
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0

- name: Launch the new EC2 Instance
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    wait: true 
    region: "{{ region }}"
    keypair: "{{ keypair_name }}"
    volumes: "{{ storage_config }}"
    count: "{{ count_instances }}"
    instance_tags: "{{ tags }}"
  register: ec2

- name: "Add new instance to inventory"
  add_host:
    name: "{{ item.public_ip }}"
    ansible_ssh_private_key_file: "{{ aws_private_ssh_key }}"
    groups: "aws"
  with_items: "{{ ec2.instances }}"

- name: "Wait for SSH is reachable"
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"
